name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.9 # Define the elixir version [required]
        otp-version: 22 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
    - name: Coverage
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.coveralls_token }}
        parallel: true
